# Use uma imagem base do Java
FROM openjdk:17-jdk-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o JAR gerado para dentro do container
COPY target/Patient.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
